name: Release

on:
  push:
    tags: '*'

env:
  BOOST_VERSION: 1.83.0
  OGDF_VERSION: elderberry-202309
  QT_VERSION: 6.6.1

jobs:
  create_release:
    runs-on: ubuntu-20.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      git_tag: ${{ steps.get-git-tag.outputs.name }}
    steps:
      - name: Get Git tag
        id: get-git-tag
        run: |
          GIT_REF=${{ github.ref }}
          echo "name=${GIT_REF#refs/*/}" >> $GITHUB_OUTPUT

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-git-tag.outputs.name }}
          release_name: LOOT v${{ steps.get-git-tag.outputs.name }}
          draft: true
          body: |
            The list of changes can be found [here](https://loot.readthedocs.io/en/latest/app/changelog.html).

            ## Windows

            LOOT requires a 64-bit version of Windows 10 (1809) or later and the [MSVC 2019 x64 redistributable](https://aka.ms/vs/16/release/vc_redist.x64.exe).

            The `.exe` installer will automatically download and install the redistributable if you don't already have it installed.

            [7-Zip](https://www.7-zip.org/) is required to extract the `.7z` archive on Windows 10.

            ## Linux

            LOOT requires a 64-bit version of Linux, and can be installed from [Flathub](https://flathub.org/apps/io.github.loot.loot).

            The `.tar.xz` archive is not recommended for general use as it does not include most of LOOT's runtime dependencies.

  linux:
    runs-on: ubuntu-20.04
    needs: create_release

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Get Boost metadata
        id: boost-metadata
        run: |
          BOOST_ROOT=~/boost_${BOOST_VERSION//./_}
          echo "root=$BOOST_ROOT" >> $GITHUB_OUTPUT
          echo "librarydir=${BOOST_ROOT}/stage/64/lib" >> $GITHUB_OUTPUT

      - name: Set OGDF install path
        run: echo "OGDF_INSTALL_PATH=${{ github.workspace }}/ogdf-${{ env.OGDF_VERSION }}-install" >> $GITHUB_ENV

      - name: Boost cache
        id: boost-cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.boost-metadata.outputs.root }}/boost
            ${{ steps.boost-metadata.outputs.root }}/stage
          key: ${{ runner.os }}-Boost-${{ env.BOOST_VERSION }}

      - name: OGDF cache
        id: ogdf-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.OGDF_INSTALL_PATH }}
          key: ${{ runner.os }}-ogdf-${{ env.OGDF_VERSION }}

      - name: Install C++ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-upgrade \
            libtbb-dev \
            g++-10 \
            build-essential \
            libgl1-mesa-dev \
            gettext

      - name: Download & build Boost
        run: |
          wget https://raw.githubusercontent.com/Ortham/ci-scripts/2.1.2/install_boost.py
          python install_boost.py --directory ~ --boost-version $BOOST_VERSION -a 64 -t gcc-10 locale
        if: steps.boost-cache.outputs.cache-hit != 'true'

      - name: Get ICU
        id: get-icu
        run: |
          wget https://github.com/unicode-org/icu/releases/download/release-71-1/icu4c-71_1-Ubuntu20.04-x64.tgz
          tar -xf icu4c-71_1-Ubuntu20.04-x64.tgz

          echo "root=${{ github.workspace }}/icu/usr/local" >> $GITHUB_OUTPUT

      - name: Download Qt
        id: qt-metadata
        run: |
          python -m pip install aqtinstall
          aqt install-qt linux desktop $QT_VERSION gcc_64
          echo "root=${{ github.workspace }}/$QT_VERSION/gcc_64" >> $GITHUB_OUTPUT

      - name: Download and build OGDF
        run: |
          curl -sSfLO https://github.com/ogdf/ogdf/archive/refs/tags/${OGDF_VERSION}.zip
          unzip ${OGDF_VERSION}.zip -d .

          mkdir ogdf-${OGDF_VERSION}/build
          cd ogdf-${OGDF_VERSION}/build

          export CXX="g++-10" CC="gcc-10"
          cmake .. -DCMAKE_INSTALL_PREFIX="${OGDF_INSTALL_PATH}"
          cmake --build .
          cmake --install .
        if: steps.ogdf-cache.outputs.cache-hit != 'true'

      - name: Run CMake
        run: |
          mkdir build
          cd build
          export CXX="g++-10" CC="gcc-10"
          cmake .. -DBOOST_ROOT=${{ steps.boost-metadata.outputs.root }} -DBOOST_LIBRARYDIR=${{ steps.boost-metadata.outputs.librarydir }} -DQt6_ROOT="${{ steps.qt-metadata.outputs.root }}" -DOGDF_ROOT="${{ env.OGDF_INSTALL_PATH }}" -DICU_ROOT="${{ steps.get-icu.outputs.root }}"
          make LOOT

      - name: Install packages for building docs
        run: |
          python -m pip install -r docs/requirements.txt
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build docs
        run: sphinx-build -b html docs build/docs/html

      - name: Build translation message object files
        run: python scripts/po_to_mo.py

      - name: Get descriptive LOOT version
        id: get-loot-version
        run: |
          GIT_DESCRIBE=$(git describe --tags --long --abbrev=7)
          GIT_REF=${{ github.ref }}
          LOOT_DESC_REF=${GIT_DESCRIBE}_${GIT_REF#refs/*/}
          LOOT_SAFE_DESC_REF=${LOOT_DESC_REF//[\/<>\"|]/_}
          echo "version=$LOOT_SAFE_DESC_REF" >> $GITHUB_OUTPUT

      - name: Build archive
        id: build-archive
        run: |
          FILENAME="loot_${{ needs.create_release.outputs.git_tag }}-Linux.tar.xz"
          export PATH="${{ steps.qt-metadata.outputs.root }}/bin:$PATH"

          python scripts/archive.py . "${{ needs.create_release.outputs.git_tag }}"
          mv "build/loot_${{ steps.get-loot-version.outputs.version }}.tar.xz" "build/$FILENAME"

          echo "filename=$FILENAME" >> $GITHUB_OUTPUT

      - name: Upload archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: build/${{ steps.build-archive.outputs.filename }}
          asset_name: ${{ steps.build-archive.outputs.filename }}
          asset_content_type: application/octet-stream

  windows:
    runs-on: windows-2019
    needs: create_release

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get Boost metadata
        id: boost-metadata
        run: |
          $BOOST_ROOT="${{ github.workspace }}/boost_" + $env:BOOST_VERSION -replace "\.", "_"
          echo "root=$BOOST_ROOT" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          echo "librarydir=${BOOST_ROOT}/stage/64/lib" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Set OGDF install path
        shell: bash
        run: echo "OGDF_INSTALL_PATH=${{ github.workspace }}/ogdf-${{ env.OGDF_VERSION }}-install" >> $GITHUB_ENV

      - name: Boost cache
        id: boost-cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.boost-metadata.outputs.root }}/boost
            ${{ steps.boost-metadata.outputs.root }}/stage
          key: ${{ runner.os }}-x64-Boost-${{ env.BOOST_VERSION }}

      - name: OGDF cache
        id: ogdf-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.OGDF_INSTALL_PATH }}
          key: ${{ runner.os }}-x64-ogdf-${{ env.OGDF_VERSION }}

      - name: Download and extract svg_to_ico
        run: |
          curl -sfSLO 'https://github.com/Ortham/svg_to_ico/releases/download/1.1.0/svg_to_ico.7z'
          7z e -y svg_to_ico.7z

      - name: Generate ICO file
        run: .\svg_to_ico.exe -i resources\icons\loot.svg -o build\icon\icon.ico

      - name: Download & build Boost
        run: |
          curl -sSfLO https://raw.githubusercontent.com/Ortham/ci-scripts/2.1.2/install_boost.py
          python install_boost.py --directory ${{ github.workspace }} --boost-version ${{ env.BOOST_VERSION }} -a 64 locale
        if: steps.boost-cache.outputs.cache-hit != 'true'

      - name: Download and build OGDF
        run: |
          curl -sSfLO https://github.com/ogdf/ogdf/archive/refs/tags/${env:OGDF_VERSION}.zip
          Expand-Archive -Path "${env:OGDF_VERSION}.zip" -DestinationPath .

          mkdir ogdf-${env:OGDF_VERSION}/build
          cd ogdf-${env:OGDF_VERSION}/build
          cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX="${env:OGDF_INSTALL_PATH}"
          cmake --build . --config Release
          cmake --install . --config Release
        if: steps.ogdf-cache.outputs.cache-hit != 'true'

      - name: Download Qt
        id: qt-metadata
        run: |
          python -m pip install aqtinstall

          aqt install-qt windows desktop ${env:QT_VERSION} win64_msvc2019_64
          echo "root=${{ github.workspace }}/${env:QT_VERSION}/msvc2019_64" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Run CMake
        run: |
          cd build
          cmake .. -G "Visual Studio 16 2019" -A x64 -DBOOST_ROOT="${{ steps.boost-metadata.outputs.root }}" -DBOOST_LIBRARYDIR="${{ steps.boost-metadata.outputs.librarydir }}" -DQt6_ROOT="${{ steps.qt-metadata.outputs.root }}" -DOGDF_ROOT="${{ env.OGDF_INSTALL_PATH }}"
          cmake --build . --config Release

      - name: Install packages for building docs
        run: |
          python -m pip install -r docs/requirements.txt

      - name: Build docs
        run: sphinx-build -b html docs build\docs\html

      - name: Build translation message object files
        run: python scripts/po_to_mo.py

      - name: Get descriptive LOOT version
        id: get-loot-version
        shell: bash
        run: |
          GIT_DESCRIBE=$(git describe --tags --long --abbrev=7)
          GIT_REF=${{ github.ref }}
          LOOT_DESC_REF=${GIT_DESCRIBE}_${GIT_REF#refs/*/}
          LOOT_SAFE_DESC_REF=${LOOT_DESC_REF//[\/<>\"|]/_}
          echo "version=$LOOT_SAFE_DESC_REF" >> $GITHUB_OUTPUT

      - name: Get LOOT artifact basename
        id: get-artifact-basename
        shell: bash
        run: |
          echo "basename=loot_${{ needs.create_release.outputs.git_tag }}-win64" >> $GITHUB_OUTPUT

      - name: Build archive
        run: |
          $env:PATH="${{ steps.qt-metadata.outputs.root }}/bin;$env:PATH"
          python scripts\archive.py . ${{ needs.create_release.outputs.git_tag }}
          mv "build\loot_${{ steps.get-loot-version.outputs.version }}.7z" "build\${{ steps.get-artifact-basename.outputs.basename }}.7z"

      - name: Build installer
        run: |
          scripts\build_installer.ps1

          mv "build\LOOT Installer.exe" "build\${{ steps.get-artifact-basename.outputs.basename }}.exe"

      - name: Upload Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: build\${{ steps.get-artifact-basename.outputs.basename }}.7z
          asset_name: ${{ steps.get-artifact-basename.outputs.basename }}.7z
          asset_content_type: application/x-7z-compressed

      - name: Upload Installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: build\${{ steps.get-artifact-basename.outputs.basename }}.exe
          asset_name: ${{ steps.get-artifact-basename.outputs.basename }}.exe
          asset_content_type: application/octet-stream
